# Generated by Django 4.2.5 on 2023-10-06 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_of_upvotes", models.IntegerField(default=0)),
                (
                    "commented_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_project", models.CharField(max_length=255)),
                ("description_of_project", models.TextField()),
                ("views", models.IntegerField(default=0)),
                ("thumbnail_of_project", models.ImageField(upload_to="thumbnails/")),
                ("image1", models.ImageField(blank=True, upload_to="project_images/")),
                ("image2", models.ImageField(blank=True, upload_to="project_images/")),
                ("image3", models.ImageField(blank=True, upload_to="project_images/")),
                ("video", models.URLField(blank=True)),
                ("link1", models.URLField(blank=True)),
                ("link2", models.URLField(blank=True)),
                ("link3", models.URLField(blank=True)),
                ("report", models.FileField(upload_to="reports/")),
                ("no_of_upvotes", models.IntegerField(default=0)),
                ("no_of_comments", models.IntegerField(default=0)),
                (
                    "plag_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "plagiarized_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.projectentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Technologies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="upvote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upvoted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "upvoted_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.projectentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poc_name", models.CharField(max_length=255)),
                ("poc_email", models.EmailField(max_length=254)),
                ("team_members_details", models.CharField(max_length=1000)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.collegespoc",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.course",
                    ),
                ),
                (
                    "course_coordinator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.coursecoordinator",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project_Technologies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.projectentry",
                    ),
                ),
                (
                    "technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.technologies",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project_Team_Members",
            fields=[
                (
                    "team_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.projectentry",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.student_details",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="comment_reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "replied_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "replied_on",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.comment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="comment_like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "liked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liked_on",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.comment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="commented_on",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.projectentry"
            ),
        ),
    ]
