# Generated by Django 4.2.5 on 2023-10-04 15:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('no_team_mates', models.IntegerField(max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
                ('plag_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('name_of_project', models.CharField(max_length=255)),
                ('description_of_project', models.TextField()),
                ('thumbnail_of_project', models.ImageField(upload_to='thumbnails/')),
                ('image1', models.ImageField(blank=True, upload_to='project_images/')),
                ('image2', models.ImageField(blank=True, upload_to='project_images/')),
                ('image3', models.ImageField(blank=True, upload_to='project_images/')),
                ('video', models.URLField(blank=True)),
                ('link1', models.URLField(blank=True)),
                ('link2', models.URLField(blank=True)),
                ('link3', models.URLField(blank=True)),
                ('report', models.FileField(upload_to='reports/')),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poc_name', models.CharField(max_length=255)),
                ('poc_email', models.EmailField(max_length=254)),
                ('team_members_details', models.CharField(max_length=1000)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.course')),
                ('course_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.coursecoordinator')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectentry')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.technologies')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Team_Members',
            fields=[
                ('team_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectentry')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.student_details')),
            ],
        ),
    ]
