# Generated by Django 4.2.5 on 2023-10-04 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_collegespoc_visitor_remove_college_baseuser_ptr_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_upvotes', models.IntegerField(default=0)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.visitor')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectentry',
            name='no_team_mates',
        ),
        migrations.AddField(
            model_name='projectentry',
            name='no_of_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectentry',
            name='no_of_upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectentry',
            name='plagiarized_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectentry'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.collegespoc'),
        ),
        migrations.CreateModel(
            name='upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvoted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.visitor')),
                ('upvoted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectentry')),
            ],
        ),
        migrations.CreateModel(
            name='comment_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.visitor')),
                ('replied_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.comment')),
            ],
        ),
        migrations.CreateModel(
            name='comment_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.visitor')),
                ('liked_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectentry'),
        ),
    ]
