# Generated by Django 4.2.5 on 2023-10-04 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeSpoc',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('affiliated_univ', models.CharField(max_length=255)),
                ('univ_address', models.TextField()),
                ('spoc_mail', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('profile_pic', models.ImageField(upload_to='profile_pics/')),
                ('aishe_code', models.CharField(max_length=20)),
                ('abbrevation', models.CharField(blank=True, max_length=10, null=True)),
                ('letter_of_approval', models.FileField(upload_to='letters_of_approval/')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.baseuser',),
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(upload_to='profile_pics/')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.baseuser',),
        ),
        migrations.RemoveField(
            model_name='college',
            name='baseuser_ptr',
        ),
        migrations.AlterField(
            model_name='college_course',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.collegespoc'),
        ),
        migrations.AlterField(
            model_name='coursecoordinator',
            name='affiliated_college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.collegespoc'),
        ),
    ]
