# Generated by Django 4.2.5 on 2023-10-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_comment_remove_projectentry_no_team_mates_and_more'),
        ('accounts', '0002_collegespoc_visitor_remove_college_baseuser_ptr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
    ]
